#!/bin/sh

# Check required variables for GCS
[ -z "$GCLOUD_SA_KEY" ] && { echo "GCLOUD_SA_KEY is required"; exit 1; }
[ -z "$GCLOUD_PROJECT_ID" ] && { echo "GCLOUD_PROJECT_ID is required"; exit 1; }
[ -z "$DOCS_OUTPUT_DIRECTORY" ] && { echo "AGLIO_DOCS_DIRECTORY is required"; exit 1; }
[ -z "$GCS_BUCKET" ] && { echo "GCS_BUKET is required"; exit 1; }
[ -z "$GCS_PREFIX" ] && { echo "GCS_PREFIX is required"; exit 1; }

# create SA key file
echo $GCLOUD_SA_KEY | base64 -d > /tmp/key.json

# set Rclone variables
export RCLONE_GCS_PROJECT_NUMBER=${GCLOUD_PROJECT_ID}
export RCLONE_GCS_SERVICE_ACCOUNT_FILE=/tmp/key.json

# create Rclone config
rclone config create remote gcs > /dev/null 2>&1

# upload files to GCS
rclone sync ${DOCS_OUTPUT_DIRECTORY} remote:${GCS_BUCKET}${GCS_PREFIX} > /dev/null 2>&1

# list files for logging purposes
echo "Uploaded files:"
rclone ls remote:${GCS_BUKET}${GCS_PREFIX}
